name: Last dispatch event  
description: Last dispatch event  

inputs:
  ACCESS_TOKEN:
    description: Access token
    required: true
  EVENT_TYPE:
    description: Event type name
    required: true
  SUCCESS_DESCRIPTION:
    description: Success description
    required: true
  ERROR_DESCRIPTION:
    description: Error description
    required: true
  STATUSES_HREF:
    description: Statuses link
    required: true
  RESULTS_OF_JOBS:
    description: Concatenation of job results
    required: true

runs:
  using: composite
  steps: 
    - name: Show
      shell: bash
      run: |
        JSON=${{ inputs.RESULTS_OF_JOBS }}
        echo "::set-output name=value::$(echo $JSON | jq -c '.states')"

    # - name: Success status
    #   if: ${{ !contains(fromJSON(inputs.RESULTS_OF_JOBS)), 'failure') }}
    #   uses: ./.github/actions/dispatch-event
    #   with:
    #     ACCESS_TOKEN: ${{ inputs.ACCESS_TOKEN }}
    #     REPOSITORY: 'adroaldoneto/gha-dispatch-event-initiator'
    #     DATA: '{"event_type": "${{ inputs.EVENT_TYPE }}", "client_payload": { "state": "success", "description": "${{ inputs.SUCCESS_DESCRIPTION }}", "statuses_href": "${{ inputs.statuses_href }}" }}'
    
    # - name: Failure status
    #   if: ${{ contains(toJSON(inputs.RESULTS_OF_JOBS).states, 'failure') }}
    #   uses: ./.github/actions/dispatch-event
    #   with:
    #     ACCESS_TOKEN: ${{ inputs.ACCESS_TOKEN }}
    #     REPOSITORY: 'adroaldoneto/gha-dispatch-event-initiator'
    #     DATA: '{"event_type": "${{ inputs.EVENT_TYPE }}", "client_payload": { "state": "failure", "description": "${{ inputs.ERROR_DESCRIPTION }}", "statuses_href": "${{ inputs.statuses_href }}" }}'